replicaCount: 3

image:
  repository: platformd
  tag: dev
  pullPolicy: IfNotPresent

service:
  httpPort: 8080
  grpcPort: 50051

resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits:   { cpu: 250m, memory: 128Mi }